webapp/models.py
from flask.ext.sqlalchemy import SQLAlchemy

from webapp.extensions import bcrypt

db = SQLAlchemy()

class User(db.Model):
    id = db.Column(db.Integer(), primary_key=True)
    username = db.Column(db.String(255))
    password = db.Column(db.String(255))
    posts = db.relationship(
        'Post',
        backref='user',
        lazy='dynamic'
    )

    def set_password(self, password):
        self.password = bcrypt.generate_password_hash(password)

    def check_password(self, password):
        return bcrypt.check_password_hash(self.password,
                password)

    def get_id(self):
        return unicode(self.id)


# make intermediate join table
tags = db.Table('post_tags',
    db.Column('post_id', db.Integer, db.ForeignKey('post.id')),
    db.Column('tag_id', db.Integer, db.ForeignKey('tag.id'))
    )

class Post(db.Model):
  id = db.Column(db.Integer(), primary_key=True)
  title = db.Column(db.String(255))
  text = db.Column(db.Text())
  publish_date = db.Column(db.DateTime())
  comments = db.relationship(
      'Comment',
      backref='post',
      lazy='dynamic'
  )
  user_id = db.Column(db.Integer(), db.ForeignKey('user.id'))
  tags = db.relationship(
      'Tag',
      secondary=tags,
      backref=db.backref('posts', lazy='dynamic')
  )


class Tag(db.Model):
  id = db.Column(db.Integer, primary_key=True)
  title = db.Column(db.String(255))


class Comment(db.Model):
  id = db.Column(db.Integer(), primary_key=True)
  name = db.Column(db.String(255))
  text = db.Column(db.Text())
  date = db.Column(db.DateTime())
  post_id = db.Column(db.Integer(),
      db.ForeignKey('post.id'))

class Reminder(db.Model):
  id = db.Column(db.Integer(), primary_key=True)
  date = db.Column(db.DateTime())
  email = db.Column(db.String())
  text = db.Column(db.Text())

  def __repr__(self):
      return "<Reminder '{}'>".format(self.text[:20])

webapp/forms.py
from flask.ext.wtf import Form, RecaptchaField
from wtforms import (
        StringField,
        TextAreaField,
        PasswordField,
        BooleanField)
from wtforms.validators import (
        DataRequired, Length, EqualTo, URL)

from webapp.models import User

class LoginForm(Form):
    username = StringField('Username',
            [DataRequired(), Length(max=255)])
    password = PasswordField('Password', [DataRequired()])
    remember = BooleanField("Remember Me")

    def validate(self):
        check_validate = super(LoginForm, self).validate()

        # if out validators do not pass
        if not check_validate:
            return False

        # Does our user exist?
        user = User.query.filter_by(
                username=self.username.data).first()
        if not user:
            self.username.errors.append('Invalid username or password')
            return False

        # Do the passwords match?
        if not user.check_password(self.password.data):
            self.username.errors.append(
                    'Invalid username or password')
            return False

        return True

class RegisterForm(Form):
    username = StringField('Username',
            [DataRequired(), Length(max=255)])
    password = PasswordField('Password',
            [DataRequired(), Length(min=8)])
    confirm = PasswordField('Confirm Password',
            [DataRequired(), EqualTo('password')])
    recaptcha = RecaptchaField()

    def validate(self):
        check_validate = super(RegisterForm,
                self).validate()

        # if our validators don't pass
        if not check_validate:
            return False

        user = User.query.filter_by(
                username=self.username.data).first()

        # Is the username already being used?
        if user:
            self.username.errors.append(
                    "User with that username exists!")
            return False

        return True

class PostForm(Form):
    title = StringField('Title',
            [DataRequired(), Length(max=255)])
    text = TextAreaField('Content', [DataRequired()])


class CommentForm(Form):
  name = StringField(
        'Name',
        validators=[DataRequired(), Length(max=255)]
      )
  text = TextAreaField(u'Comment', validators=[DataRequired()])

webapp/__init__.py
from flask import Flask, redirect, url_for
from flask.ext.restful import Api

from sqlalchemy import event

from webapp.config import DevConfig, TestConfig
from webapp.models import db, Reminder
from webapp.controllers.main import main_blueprint
from webapp.controllers.blog import blog_blueprint
from webapp.extensions import (
        bcrypt, login_manager, debug_toolbar, cache
        )
from webapp.controllers.rest.post import PostApi

def create_app(object_name):
    app = Flask(__name__)
    app.config.from_object(object_name)

    db.init_app(app)

    bcrypt.init_app(app)
    login_manager.init_app(app)
    debug_toolbar.init_app(app)
    cache.init_app(app)

    rest_api = Api(app)
    rest_api.add_resource(PostApi,
            '/restapi/post',
            '/restapi/post/<int:post_id>',
            endpoint='restapi')

    app.register_blueprint(main_blueprint)
    app.register_blueprint(blog_blueprint)
    return app

# make a dev app
dev_app = create_app(DevConfig)

# make a test app
test_app = create_app(TestConfig)

webapp/controllers/blog.py
import datetime

from flask import render_template, redirect, url_for, request, Blueprint
from sqlalchemy import func
from flask.ext.login import login_required

from webapp.models import db, Post, Tag, Comment, User, Tag, tags
from webapp.forms import CommentForm, PostForm
from webapp.extensions import cache

blog_blueprint = Blueprint(
        'blog',
        __name__,
        template_folder='../templates/blog',
        url_prefix='/blog'
        )

@cache.cached(timeout=600, key_prefix='sidebar_data')
def sidebar_data():
    recent = Post.query.order_by(
        Post.publish_date.desc()).limit(5).all()
    top_tags = db.session.query(
        Tag, func.count(tags.c.post_id).label('total')
        ).join(
            tags
        ).group_by(Tag).order_by('total DESC').limit(5).all()
    return recent, top_tags

@blog_blueprint.route('/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()

    if form.validate_on_submit():
        new_post = Post()
        new_post.title = form.title.data
        new_post.text = form.text.data
        new_post.publish_date = datetime.datetime.now()

        db.session.add(new_post)
        db.session.commit()
        return redirect(url_for('blog.post', post_id=new_post.id))

    recent, top_tags = sidebar_data()
    return render_template('new.html',
            form=form,
            recent=recent,
            top_tags=top_tags)

@blog_blueprint.route('/edit/<int:id>', methods=['GET', 'POST'])
def edit_post(id):
    post = Post.query.get_or_404(id)
    form = PostForm()

    if form.validate_on_submit():
        post.title = form.title.data
        post.text = form.text.data
        post.publish_date = datetime.datetime.now()

        db.session.add(post)
        db.session.commit()

        return redirect(url_for('blog.post',
            post_id=post.id))

    recent, top_tags = sidebar_data()
    return render_template('edit.html',
            form=form,
            post=post,
            recent=recent,
            top_tags=top_tags)

@blog_blueprint.route('/')
@blog_blueprint.route('/<int:page>')
@cache.cached(timeout=60)
def home(page=1):
    posts = Post.query.order_by(
        Post.publish_date.desc()
        ).paginate(page, 10)
    recent, top_tags = sidebar_data()
    return render_template(
        'home.html',
        posts=posts,
        recent=recent,
        top_tags=top_tags
     )

@blog_blueprint.route('/post/<int:post_id>', methods=('GET', 'POST'))
@blog_blueprint.route('/post/<int:post_id>/<int:page>', methods=('GET', 'POST'))
def post(post_id, page=1):
    form = CommentForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            comment = Comment()
            comment.name = form.name.data
            comment.text = form.text.data
            comment.post_id = post_id
            comment.date = datetime.datetime.now()

            db.session.add(comment)
            db.session.commit()
            return redirect(url_for('post', post_id=post.id))

    post = Post.query.get_or_404(post_id)
    tags = post.tags

    comments = post.comments.order_by(Comment.date.desc()
        ).paginate(page, 10)
    recent, top_tags = sidebar_data()

    return render_template(
        'post.html',
        post=post,
        tags=tags,
        comments=comments,
        recent=recent,
        top_tags=top_tags,
        form=form
    )

@blog_blueprint.route('/tag/<string:tag_name>')
@blog_blueprint.route('/tag/<string:tag_name>/<int:page>')
def tag(tag_name, page=1):
    tag = Tag.query.filter_by(title=tag_name).first_or_404()
    posts = tag.posts.order_by(Post.publish_date.desc()
        ).paginate(page, 10)
    recent, top_tags = sidebar_data()
    return render_template(
        'tag.html',
        tag=tag,
        posts=posts,
        recent=recent,
        top_tags=top_tags
    )

@blog_blueprint.route('/user/<string:username>')
@blog_blueprint.route('/user/<string:username>/<int:page>')
def user(username, page=1):
    user = User.query.filter_by(username=username).first_or_404()
    posts = user.posts.order_by(
        Post.publish_date.desc()
        ).paginate(page, 10)

    recent, top_tags = sidebar_data()
    return render_template(
        'user.html',
        user=user,
        posts=posts,
        recent=recent,
        top_tags=top_tags
    )

webapp/controllers/main.py
from flask import (
        render_template, redirect,
        url_for, request, Blueprint, flash)
from sqlalchemy import func
from flask.ext.login import login_user, logout_user

from webapp.forms import LoginForm, RegisterForm
from webapp.models import User, Post, Tag, tags, db

main_blueprint = Blueprint(
        'main',
        __name__,
        template_folder='../templates/main')

def sidebar_data():
    recent = Post.query.order_by(
        Post.publish_date.desc()).limit(5).all()
    top_tags = db.session.query(
        Tag, func.count(tags.c.post_id).label('total')
        ).join(
            tags
        ).group_by(Tag).order_by('total DESC').limit(5).all()
    return recent, top_tags

@main_blueprint.route('/')
def index():
    return redirect(url_for('blog.home'))

@main_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        login_user(user, remember=form.remember.data)

    recent, top_tags = sidebar_data()
    return render_template('login.html',
            form=form,
            recent=recent,
            top_tags=top_tags)

@main_blueprint.route('/logout', methods=['GET', 'POST'])
def logout():
    logout_user()

@main_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()

    if form.validate_on_submit():
        new_user = User()
        new_user.username = form.username.data
        new_user.set_password(form.password.data)

        db.session.add(new_user)
        db.session.commit()

        flash('Your user has been created, please log in.',
                category='success')

        return redirect(url_for('main.login'))

    recent, top_tags = sidebar_data()
    return render_template('register.html',
            form=form,
            recent=recent,
            top_tags=top_tags)

webapp/templates/blog/base.html
{% macro render_pagination(pagination, endpoint) %}
<nav>
  <ul class="pagination">
    {% for page in pagination.iter_pages() %}
      {% if page %}
        {% if page != pagination.page %}
          <li>
            <a href="{{ url_for(endpoint, page=page, **kwargs) }}">
              {{ page }}
            </a>
          </li>
        {% else %}
          <li><a href="">{{ page }}</a></li>
        {% endif %}
      {% else %}
        <li><a>...</a></li>
      {% endif %}
    {% endfor %}
  </ul>
</nav>
{% endmacro %}


<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, intial- scale=1">
  <title>{% block title %}Blog{% endblock%}</title>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
</head>
<body>
  <div class="container">
    <div class="jumbotron">
      <h1><a href={{ url_for('blog.home') }}>My Blog</a></h1>
      <p>Welcome to the blog!</p>
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
            <div class="alert alert-{{ category }} alert-dismissible"
                role="alert">
                <button type="button" class="close" 
                    data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
                {{ message }}
            </div>
            {% endfor %}
        {% endif %}
        {% endwith %}
    </div>
    <div class="row">
      <div class="col-sm-9">

      {% block body %}
      {% endblock %}
      </div>
      <div class="col-sm-3">
        <div class="row">
          <h5>Recent Posts</h5>
          <ul>
            {% for post in recent %}
            <li><a href="{{
              url_for('blog.post', post_id=post.id)
              }}">{{ post.title }}</a></li>
            {% endfor %}
          </ul>
      </div>
      <div class="row">
        <h5>Popular Tags</h5>
        <ul>
          {% for tag in top_tags %}
          <li><a href="{{ url_for('blog.tag', tag_name=tag[0].title) }}">
          {{ tag[0].title }}</a></li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>

<script src="{{ url_for('static', filename='js/jquery.min.js') }}">
</script>
<script src="{{ url_for('static', filename='js/bootstrap.min.js') }}">
</script>
  {% block js %}
  {% endblock %}
</body>
</html>

webapp/templates/blog/edit.html
{% extends "base.html" %}
{% block title %} Make a New Post {% endblock %}
{% block body %}
<div class="row">
    <h1 class="text-center">Create A New Post</h1>
    <form method="POST" action="{{ url_for('blog.edit_post', id=post.id) }}">
        {{ form.hidden_tag() }}
    <div class="form-group">
    {{ form.title.label }}
    {% if form.title.errors %}
        {% for e in form.title.errors %}
        <p class="help-block">{{ e }}</p>
        {% endfor %}
    {% endif %}
    {{ form.title(class_='form-control', value=post.title) }}
    </div>
    <div class="form-group">
    {{ form.text.label }}
    {{ form.text(id="editor", class_='form-control',
    value=post.text) }}
    </div>
    <input class="btn btn-primary" type="submit" value="Submit">
    </form>
</div>
{% endblock %}

{% block js %}
<script src = "//cdn.ckeditor.com/4.4.7/standard/ckeditor.js">
</script>
<script>
    CKEDITOR.replace('editor');
</script>
{% endblock %}

webapp/templates/blog/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}


{% block body %}
   {% for post in posts.items %}
    <div class="row">
      <div class="col-sm-12">
        <h1>{{ post.title }}</h1>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-12">
        {{ post.text | truncate(255) | safe }}
        <a href="{{ url_for('.post', post_id=post.id) }}">Read More</a>
      </div>
    </div>
    {% endfor %}
{{ render_pagination(posts, '.home') }}
{% endblock %}

webapp/templates/blog/new.html
{% extends "base.html" %}
{% block title %} Make a New Post {% endblock %}
{% block body %}
<div class="row">
    <h1 class="text-center">Create A New Post</h1>
    <form method="POST" action="{{ url_for('blog.new_post') }}">
        {{ form.hidden_tag() }}
    <div class="form-group">
    {{ form.title.label }}
    {% if form.title.errors %}
        {% for e in form.title.errors %}
        <p class="help-block">{{ e }}</p>
        {% endfor %}
    {% endif %}
    {{ form.title(class_='form-control') }}
    </div>
    <div class="form-group">
    {{ form.text.label }}
    {{ form.text(id="editor", class_='form-control',
    value='') }}
    </div>
    <input class="btn btn-primary" type="submit" value="Submit">
    </form>
</div>
{% endblock %}

{% block js %}
<script src = "//cdn.ckeditor.com/4.4.7/standard/ckeditor.js">
</script>
<script>
    CKEDITOR.replace('editor');
</script>
{% endblock %}

webapp/templates/blog/post.html
{% extends "base.html" %}

{% block title %}Post: {{ post.title }}{% endblock %}


{% block body %}
<h3>{{ post.title }}</h3>
<a href="{{ url_for('blog.edit_post', id=post.id) }}"
    class="btn btn-primary">Edit</a>
<a href="{{ url_for('blog.new_post', id=post.id) }}"
    class="btn btn-primary">New</a>
<p><b>By:</b>
  <a href="{{ url_for('blog.user', username=post.user.username) }}">
    {{ post.user.username }}
  </a></p>
<p><b>On:</b> {{ post.publish_date }}</p>
<p><b>Tags:</b>
{% for tag in tags %}
  <a href="{{ url_for('blog.tag', tag_name=tag.title)}}">#{{ tag.title }} </a>
{% endfor %}
</p>
<hr>
<p>{{ post.text | safe }}</p> 
<hr>
<h3>Comments:</h3>

{% for comment in comments.items %}
<p><b>Name:</b>{{ comment.name }}</p>
<p><b>Date:</b>{{ comment.date }}</p>
<p>{{ comment.text }}</p>
<hr>
{% endfor %}
{{ render_pagination(comments, 'blog.post', post_id=post.id) }}


<h3>New Comment:</h3>
<form method="POST" action="{{ url_for('blog.post', post_id=post.id) }}">
  {{ form.hidden_tag() }}
  <div class="form-group">
    {{ form.name.label }}
    {% if form.name.errors %}
      {% for e in form.name.errors %}
        <p class="help-block">{{ e }}</p>
      {% endfor %}
    {% endif %}
    {{ form.name(class_='form-control') }}
  </div>
  <div class="form-group">
    {{ form.text.label }}
    {% if form.text.errors %}
      {% for e in form.text.errors %}
        <p class="help-block">{{ e }}</p>
      {% endfor %}
    {% endif %}
    {{ form.text(class_='form-control') }}
  </div>
  <input class="btn btn-primary" type="submit" value="Add Comment">
</form>
{% endblock %}

webapp/templates/blog/tag.html
{% extends "base.html" %}

{% block title %}Tag: {{ tag.title }}{% endblock %}

{% block body %}
<h3>#{{ tag.title }}</h3>
<hr>
{% for post in posts.items %}
  <p>title: <a href="{{ url_for('blog.post', post_id=post.id) }}">
    {{ post.title }}
  </a></p>
  <p>author: <a href="{{ url_for('blog.user', username=post.user.username) }}">
    {{ post.user.username }}
  </a></p>
  <hr>
{% endfor %}
{{ render_pagination(posts, 'blog.tag', tag_name=tag.title) }}
{% endblock %}

webapp/templates/blog/user.html
{% extends "base.html" %}

{% block title %}User: {{ user.username }}{% endblock %}



{% block body %}
<h3>{{ user.username }}'s Posts:</h3>
<hr>
{% for post in posts.items %}
  <p>title: <a href="{{ url_for('.post', post_id=post.id) }}">
    {{ post.title }}
  </a></p>
  <p>tags: 
  {% for tag in post.tags %}
    <a href="{{ url_for('.tag', tag_name=tag.title) }}">
      #{{ tag.title }} 
    </a>
{% endfor %}
</p>
<hr>
{% endfor %}
{{ render_pagination(posts, '.user', username=user.username) }}
{% endblock %}